import { captureOrderAttribution, type OrderAttribution } from "@/app/order-checkout";

const TINTIM_SITE_LINK = "https://tintim.link/whatsapp/2c956a42-229f-4d21-ade6-4442f8c048ed/7522df92-bbe1-4bff-83ca-2629bba182eb";

export function tintimWhatsAppUrl(message: string, attribution?: OrderAttribution, cookies = "") {
  const url = new URL(`${TINTIM_SITE_LINK}?text=${encodeURIComponent(message)}`);
  // Tintim 1.0 decorates anchors present at init only. This result anchor is
  // mounted later: carry the same tt_* cookies explicitly, plus received params.
  // Never decode/clean the invisible suffix generated by the Tintim service.
  for (const [key, values] of Object.entries(attribution?.parameters ?? {})) {
    if (key === "text") continue;
    for (const value of values) url.searchParams.append(key, value);
  }
  for (const cookie of cookies.split(";")) {
    const separator = cookie.indexOf("=");
    const name = cookie.slice(0, separator).trim();
    if (separator < 0 || !name.startsWith("tt_")) continue;
    const key = name.slice(3);
    if (!key || url.searchParams.has(key)) continue;
    try { url.searchParams.append(key, decodeURIComponent(cookie.slice(separator + 1))); } catch { /* Malformed cookie; received URL parameters remain intact. */ }
  }
  return url.href;
}

// Contatos reutilizam a captura e os dados locais que o checkout já utiliza.
// Não grava atribuição nem cria eventos. SSR mantém um href estável.
export function tintimContactUrl(message?: string): string {
  let attribution: OrderAttribution | undefined;
  let cookies = "";
  if (typeof window !== "undefined" && typeof document !== "undefined") {
    let previous: OrderAttribution | undefined;
    try {
      const saved = JSON.parse(window.sessionStorage.getItem("luciane-order-session-v2") || "null");
      if (saved?.version === 2) previous = saved.order?.attribution;
    } catch { /* Armazenamento opcional, como no checkout. */ }
    try {
      previous ??= JSON.parse(window.localStorage.getItem("lod-first-known-attribution") || "null") ?? undefined;
    } catch { /* URL atual e cookies continuam disponíveis. */ }
    cookies = document.cookie;
    attribution = captureOrderAttribution(window.location.href, cookies, previous);
  }
  const url = new URL(tintimWhatsAppUrl(message ?? "", attribution, cookies));
  if (message === undefined) url.searchParams.delete("text");
  // O token privado de /pedido não é um parâmetro de campanha.
  url.searchParams.delete("token");
  return url.href;
}
